### ISSUE TITLE
Field or Plugin

### ISSUE THREAD

**Issue by mxub** [AugustMiller/kirby-map-field#6]
The repo says it's a field but the readme says it belongs into the plugin folder -- I'm confused

**Comment by samnabi** [comment]
It's a plugin that registers its own field behind the scenes: https://github.com/AugustMiller/kirby-map-field/blob/master/map.php#L3

As of Kirby 2.3, the [extension registry](https://getkirby.com/docs/developer-guide/plugins/registry) gives more capability to plugins so they can be easier to drop in as standalone folders.

The topic of whether custom fields should be packaged as a field or a plugin is a [subject of debate](https://github.com/distantnative/field-multiselect/issues/18).

**Comment by AugustMiller** [comment]
You're right, this could be a bit confusing, based on the name alone…

Part of the reason I chose to package it as a plugin (rather than a field, like [its predecessor](https://github.com/AugustMiller/kirby-place-field) was) is that the eventual goal is to make this a complete toolkit for storing, manipulating and rendering map-based information. As Sam noted, the registry makes this possible from a plugin, but not from a field (at least, conventionally).

Unfortunately, it may be a bit late to change the repo name, but I think for the majority of users, its core benefit is managing location data in the Panel.

Every time I implement a map, the requirements are a bit different, so it didn't make sense to come out of the gate with a suite of implementations that don't really help anyone.

Note to self: a step in the right direction would be to include a use case or working example in the Readme.

**Comment by mxub** [comment]
I guess one way to make it a plugin would be to add the ability do generate maps links or frames or something
